apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o8xvdqfte-python 
  janus-idp.io/tekton: o8xvdqfte-python
  backstage.io/kubernetes-id: o8xvdqfte-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o8xvdqfte-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml